<?php

return [
    'multipliers' => [
        'default' => 2,
        'by_code' => [
            'BIF' => 0,
            'BYR' => 0,
            'CLF' => 0,
            'CLP' => 0,
            'CVE' => 0,
            'DJF' => 0,
            'GNF' => 0,
            'IDR' => 0,
            'IQD' => 0,
            'IRR' => 0,
            'ISK' => 0,
            'JPY' => 0,
            'KMF' => 0,
            'KPW' => 0,
            'KRW' => 0,
            'LAK' => 0,
            'LBP' => 0,
            'MMK' => 0,
            'PYG' => 0,
            'RWF' => 0,
            'SLL' => 0,
            'STD' => 0,
            'UYI' => 0,
            'VND' => 0,
            'VUV' => 0,
            'XAF' => 0,
            'XOF' => 0,
            'XPF' => 0,
            'MOP' => 1,
            'BHD' => 3,
            'JOD' => 3,
            'KWD' => 3,
            'LYD' => 3,
            'OMR' => 3,
            'TND' => 3,
        ],
    ],
];
